# Binary Classifier #

In [1]:
import numpy as np
import pandas as pd

In [2]:
X_final = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/X_for_testing.csv')
y_final = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/y_for_classification_test.csv')

X_sample = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/X_for_sample_testing.csv')
y_sample = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/y_classification_sample.csv')

## Smote Random Forest Classifier - sample data ##

In [ ]:
#realized smote was meant for the cancelled data and this is not the cancelled data..

In [33]:
# check version number
import imblearn

In [34]:
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

In [35]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.20, random_state=1)

In [6]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_sample, y_sample)

In [7]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [37]:
#Create a Gaussian Classifier
clf_forest=RandomForestClassifier(n_jobs=-1)

In [38]:
#Train the model using the training sets y_pred=clf.predict(X_test)
clf_forest.fit(X_train,y_train)

RandomForestClassifier(n_jobs=-1)

In [39]:
y_pred_smote=clf_forest.predict(X_test)

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_smote)) 

              precision    recall  f1-score   support

           0       0.68      0.92      0.78     41047
           1       0.59      0.22      0.32     23051

    accuracy                           0.66     64098
   macro avg       0.63      0.57      0.55     64098
weighted avg       0.64      0.66      0.61     64098



In [41]:
from sklearn.metrics import (confusion_matrix, roc_auc_score) 

In [42]:
cm = confusion_matrix(y_test, y_pred_smote)  
print ("Confusion Matrix : \n", cm)  

Confusion Matrix : 
 [[37576  3471]
 [18056  4995]]


In [43]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

pc = precision_score(y_test, y_pred_smote) 
rc = recall_score(y_test, y_pred_smote) 
f1 = f1_score(y_test, y_pred_smote) 

print ("Precision Score : \n", pc)
print ("Recall Score : \n", rc)
print ("F1 Score : \n", f1)

Precision Score : 
 0.5900070871722183
Recall Score : 
 0.21669341894060995
F1 Score : 
 0.31697179300060285


## Smote Random Forest Classifier - test data##

In [44]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=1)

In [45]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_final, y_final)

In [46]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [47]:
#Create a Gaussian Classifier
clf_forest=RandomForestClassifier(n_jobs=-1)

In [48]:
#Train the model using the training sets y_pred=clf.predict(X_test)
clf_forest.fit(Xs_train,ys_train)

RandomForestClassifier(n_jobs=-1)

In [49]:
y_pred_smote=clf_forest.predict(X_test)

In [50]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_smote)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8413
           1       1.00      1.00      1.00      4264

    accuracy                           1.00     12677
   macro avg       1.00      1.00      1.00     12677
weighted avg       1.00      1.00      1.00     12677



In [51]:
from sklearn.metrics import (confusion_matrix, roc_auc_score) 

In [52]:
cm = confusion_matrix(y_test, y_pred_smote)  
print ("Confusion Matrix : \n", cm)  

Confusion Matrix : 
 [[8413    0]
 [   0 4264]]


## Naive Bayes - sample data ##

In [5]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.20, random_state=1)

In [6]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_sample, y_sample)

In [ ]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [ ]:
from sklearn.naive_bayes import GaussianNB  

In [ ]:
gnb = GaussianNB() 

In [ ]:
gnb.fit(X_train, y_train)

In [ ]:
y_predNB = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

pc = precision_score(y_test, y_predNB) 
rc = recall_score(y_test, y_predNB) 
f1 = f1_score(y_test, y_predNB) 

print ("Precision Score : \n", pc)
print ("Recall Score : \n", rc)
print ("F1 Score : \n", f1)

## Naive Bayes - test data ##

In [ ]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.20, random_state=1)

In [ ]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_sample, y_sample)

In [ ]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [ ]:
gnb = GaussianNB() 

In [ ]:
gnb.fit(X_train, y_train)

In [ ]:
y_predNB = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

pc = precision_score(y_test, y_predNB) 
rc = recall_score(y_test, y_predNB) 
f1 = f1_score(y_test, y_predNB) 

print ("Precision Score : \n", pc)
print ("Recall Score : \n", rc)
print ("F1 Score : \n", f1)

## SVM - sample data ##

In [3]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.20, random_state=1)

In [54]:
# transform the dataset - only if it were cancelled data 
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_sample, y_sample)

In [16]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [4]:
#Import svm model
from sklearn import svm

In [5]:
#Create a svm Classifier
clf_poly = svm.SVC(kernel='poly', C=1) # polynomial kernel

In [6]:
#Train the model using the training sets
clf_poly.fit(X_train, y_train)

In [ ]:
#Predict the response for test dataset
y_pred_poly = clf_poly.predict(X_test)

In [ ]:
y_pred_poly

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

pc = precision_score(y_test, y_pred_poly) 
rc = recall_score(y_test, y_pred_poly) 
f1 = f1_score(y_test, y_pred_poly) 

print ("Precision Score : \n", pc)
print ("Recall Score : \n", rc)
print ("F1 Score : \n", f1)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred_poly)

In [ ]:
#Create a svm Classifier
clf_rbf = svm.SVC(kernel='rbf') # rbf Kernel

In [ ]:
#Train the model using the training sets
clf_rbf.fit(Xs_train, ys_train)

In [31]:
#Predict the response for test dataset
y_pred_rbf = clf_rbf.predict(X_test)

In [32]:
confusion_matrix(y_test, y_pred_rbf)

array([[8413,    0],
       [   0, 4264]])

In [ ]:
#Create a svm Classifier
clf_sig = svm.SVC(kernel='sigmoid') # sigmoid Kernel

In [ ]:
#Train the model using the training sets
clf_sig.fit(X_train, y_train)

In [ ]:
#Predict the response for test dataset
y_pred_sig = clf_sig.predict(X_test)

In [ ]:
confusion_matrix(y_test, y_pred_sig)