# Binary Classifier #

In [3]:
import numpy as np
import pandas as pd

In [4]:
X_final = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/X_for_testing.csv')
y_final = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/y_for_classification_test.csv')

X_sample = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/X_for_sample_testing.csv')
y_sample = pd.read_csv('/Users/zumiis/bootcamp_git/midterm/vscode_files/y_classification_sample.csv')

## Smote Random Forest Classifier - sample data ##

In [3]:
# check version number
import imblearn

In [14]:
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

In [5]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.20, random_state=1)

In [6]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_sample, y_sample)

In [7]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [9]:
#Create a Gaussian Classifier
clf_forest=RandomForestClassifier(n_jobs=-1)

In [10]:
#Train the model using the training sets y_pred=clf.predict(X_test)
clf_forest.fit(Xs_train,ys_train)

RandomForestClassifier(n_jobs=-1)

In [11]:
y_pred_smote=clf_forest.predict(X_test)

In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_smote)) 

              precision    recall  f1-score   support

           0       0.92      0.91      0.91     41047
           1       0.84      0.85      0.85     23051

    accuracy                           0.89     64098
   macro avg       0.88      0.88      0.88     64098
weighted avg       0.89      0.89      0.89     64098



In [13]:
from sklearn.metrics import (confusion_matrix, roc_auc_score) 

In [14]:
cm = confusion_matrix(y_test, y_pred_smote)  
print ("Confusion Matrix : \n", cm)  

Confusion Matrix : 
 [[37290  3757]
 [ 3357 19694]]


In [15]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

pc = precision_score(y_test, y_pred_smote) 
rc = recall_score(y_test, y_pred_smote) 
f1 = f1_score(y_test, y_pred_smote) 

print ("Precision Score : \n", pc)
print ("Recall Score : \n", rc)
print ("F1 Score : \n", f1)

Precision Score : 
 0.8397936122126988
Recall Score : 
 0.8543664049282027
F1 Score : 
 0.8470173325878456


## Smote Random Forest Classifier - test data##

In [16]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=1)

In [17]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_final, y_final)

In [18]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [19]:
#Create a Gaussian Classifier
clf_forest=RandomForestClassifier(n_jobs=-1)

In [20]:
#Train the model using the training sets y_pred=clf.predict(X_test)
clf_forest.fit(Xs_train,ys_train)

RandomForestClassifier(n_jobs=-1)

In [21]:
y_pred_smote=clf_forest.predict(X_test)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_smote)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8413
           1       1.00      1.00      1.00      4264

    accuracy                           1.00     12677
   macro avg       1.00      1.00      1.00     12677
weighted avg       1.00      1.00      1.00     12677



In [23]:
from sklearn.metrics import (confusion_matrix, roc_auc_score) 

In [24]:
cm = confusion_matrix(y_test, y_pred_smote)  
print ("Confusion Matrix : \n", cm)  

Confusion Matrix : 
 [[8413    0]
 [   0 4264]]


In [ ]:
#seems too good to be true..

## Naive Bayes - sample data ##

In [5]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.20, random_state=1)

In [6]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_sample, y_sample)

In [ ]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [ ]:
from sklearn.naive_bayes import GaussianNB  

In [ ]:
gnb = GaussianNB() 

In [ ]:
gnb.fit(X_train, y_train)

In [ ]:
y_predNB = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

pc = precision_score(y_test, y_predNB) 
rc = recall_score(y_test, y_predNB) 
f1 = f1_score(y_test, y_predNB) 

print ("Precision Score : \n", pc)
print ("Recall Score : \n", rc)
print ("F1 Score : \n", f1)

## Naive Bayes - test data ##

In [ ]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.20, random_state=1)

In [ ]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_sample, y_sample)

In [ ]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [ ]:
gnb = GaussianNB() 

In [ ]:
gnb.fit(X_train, y_train)

In [ ]:
y_predNB = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

pc = precision_score(y_test, y_predNB) 
rc = recall_score(y_test, y_predNB) 
f1 = f1_score(y_test, y_predNB) 

print ("Precision Score : \n", pc)
print ("Recall Score : \n", rc)
print ("F1 Score : \n", f1)

## SVM - test data ##

In [12]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=1)

In [15]:
# transform the dataset
oversample = SMOTE()
Xs, ys = oversample.fit_resample(X_final, y_final)

In [16]:
# split the transformed dataset
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.20, random_state=1)

In [17]:
#Import svm model
from sklearn import svm

In [18]:
#Create a svm Classifier
clf_poly = svm.SVC(kernel='poly', C=1) # polynomial kernel

In [24]:
#Train the model using the training sets
clf_poly.fit(Xs_train, ys_train)

SVC(C=1, kernel='poly')

In [25]:
#Predict the response for test dataset
y_pred_poly = clf_poly.predict(X_test)

In [26]:
y_pred_poly

array([1, 0, 1, ..., 0, 0, 0])

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
confusion_matrix(y_test, y_pred_poly)

array([[8413,    0],
       [   0, 4264]])

In [29]:
#Create a svm Classifier
clf_rbf = svm.SVC(kernel='rbf') # rbf Kernel

In [30]:
#Train the model using the training sets
clf_rbf.fit(Xs_train, ys_train)

SVC()

In [31]:
#Predict the response for test dataset
y_pred_rbf = clf_rbf.predict(X_test)

In [32]:
confusion_matrix(y_test, y_pred_rbf)

array([[8413,    0],
       [   0, 4264]])

In [ ]:
#Create a svm Classifier
clf_sig = svm.SVC(kernel='sigmoid') # sigmoid Kernel

In [ ]:
#Train the model using the training sets
clf_sig.fit(X_train, y_train)

In [ ]:
#Predict the response for test dataset
y_pred_sig = clf_sig.predict(X_test)

In [ ]:
confusion_matrix(y_test, y_pred_sig)